# Generated by Django 3.1.7 on 2021-06-22 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20210622_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ManyToManyField(related_name='notifications_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
