# Generated by Django 3.1.7 on 2021-06-12 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moviechoose', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('slug', models.CharField(max_length=100, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_name', to='moviechoose.movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movietheater_name', to='moviechoose.movietheater')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_time', to='moviechoose.sessions')),
            ],
        ),
    ]
