# Generated by Django 3.1.7 on 2021-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=500)),
                ('genre', models.IntegerField(blank=True, null=True)),
                ('overview', models.CharField(max_length=1000, null=True)),
                ('poster_path', models.CharField(max_length=500, null=True)),
                ('slug', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTheater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=80, null=True)),
                ('movies', models.ManyToManyField(to='moviechoose.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_times', models.CharField(max_length=1000, null=True)),
                ('movie', models.ManyToManyField(to='moviechoose.Movie')),
                ('theater', models.ManyToManyField(to='moviechoose.MovieTheater')),
            ],
        ),
    ]
