# Generated by Django 3.1.7 on 2021-06-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviechoose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietheater',
            name='slug',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
