# Generated by Django 2.2.5 on 2021-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviechoose', '0005_ratings_rater'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietheater',
            name='release_date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
