# Generated by Django 2.2.5 on 2021-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviechoose', '0006_movietheater_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietheater',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
